server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Магія SPA: якщо файлу немає, віддаємо index.html
        try_files $uri $uri/ /index.html;
    }

    # Кешування статичних файлів для максимальної швидкості
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}